pipeline:
  build:
    image: node:latest
    commands: 
    - npm install
    - npm build-prod build
plugin:
  name: Azure Web Apps
  desc: Deploy or update a project on Azure Web Apps
  type: deploy
  image: plugins/drone-azure-web-apps
  labels:
    - azure
    - web
    - apps
deploy:
  azure_web_apps:
    username: ecaterina.mirza@workland.com
    password: Tinkulita1990
    site: tinka-ci-example
    force: true
